#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Clockwise.Droid.Resource", IsApplication=true)]

namespace Clockwise.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_module_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gradient_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int off_toggle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int on_toggle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pulldown = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int setting_toggle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int settings_button = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int RepeatSelectorLayout = 2131099655;
			
			// aapt resource value: 0x7f060017
			public const int add_module_button = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int alarm_toggle = 2131099673;
			
			// aapt resource value: 0x7f060006
			public const int ampm = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int clock_settings = 2131099649;
			
			// aapt resource value: 0x7f060013
			public const int fridayInput = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int hour = 2131099652;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayout1 = 2131099676;
			
			// aapt resource value: 0x7f060005
			public const int minute = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int mondayInput = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int picker_holder = 2131099650;
			
			// aapt resource value: 0x7f060016
			public const int pulldown = 2131099670;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int repeatDaysInput = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int saturdayInput = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int setting_title = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int settings = 2131099672;
			
			// aapt resource value: 0x7f060009
			public const int sundayInput = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int thursdayInput = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int timescrollers = 2131099651;
			
			// aapt resource value: 0x7f06001b
			public const int toggle = 2131099675;
			
			// aapt resource value: 0x7f06000d
			public const int tuesdayInput = 2131099661;
			
			// aapt resource value: 0x7f06001d
			public const int view1 = 2131099677;
			
			// aapt resource value: 0x7f060010
			public const int view10 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int view11 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int view12 = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int view7 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int view8 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int view9 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int wednesdayInput = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int module_setting_row = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int save_button = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int weather_settings = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
