#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Clockwise.Droid.Resource", IsApplication=true)]

namespace Clockwise.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int news_categories_array = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int snooze_values = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_module_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int alarm_display_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int alarm_off = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int alarm_on = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cancel_create_module = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int circle_high_res = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int countdown_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int create_module_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int delete = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int edit_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int gradient_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_alarm_white_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int news_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int off_toggle = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int on_toggle = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int plus = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pulldown = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int reddit_icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int setting_toggle = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int settings_about = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int settings_button = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int settings_order = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int settings_snooze = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int settings_speech = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int settings_tone = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int todo_icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int traffic_icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int twitter_icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int up_icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int weather_icon = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070048
			public const int RepeatSelectorLayout = 2131165256;
			
			// aapt resource value: 0x7f070060
			public const int about = 2131165280;
			
			// aapt resource value: 0x7f07002d
			public const int addCountdown = 2131165229;
			
			// aapt resource value: 0x7f07001f
			public const int addNews = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int addReddit = 2131165219;
			
			// aapt resource value: 0x7f070080
			public const int addReminderButton = 2131165312;
			
			// aapt resource value: 0x7f070031
			public const int addReminders = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int addTraffic = 2131165236;
			
			// aapt resource value: 0x7f070028
			public const int addTwitter = 2131165224;
			
			// aapt resource value: 0x7f070018
			public const int addWeather = 2131165208;
			
			// aapt resource value: 0x7f070062
			public const int add_module_button = 2131165282;
			
			// aapt resource value: 0x7f070067
			public const int alarm_display_scroller = 2131165287;
			
			// aapt resource value: 0x7f070002
			public const int alarm_status = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int alarm_time = 2131165187;
			
			// aapt resource value: 0x7f070064
			public const int alarm_toggle = 2131165284;
			
			// aapt resource value: 0x7f070068
			public const int alarm_viewer = 2131165288;
			
			// aapt resource value: 0x7f070078
			public const int amountInput = 2131165304;
			
			// aapt resource value: 0x7f070077
			public const int amountText = 2131165303;
			
			// aapt resource value: 0x7f070047
			public const int ampm = 2131165255;
			
			// aapt resource value: 0x7f07000f
			public const int cancel_button = 2131165199;
			
			// aapt resource value: 0x7f070075
			public const int categoryText = 2131165301;
			
			// aapt resource value: 0x7f070042
			public const int clock_settings = 2131165250;
			
			// aapt resource value: 0x7f07002b
			public const int countdownRow = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int countdown_desc = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int countdown_settings = 2131165230;
			
			// aapt resource value: 0x7f070010
			public const int create_module_title = 2131165200;
			
			// aapt resource value: 0x7f070086
			public const int currentTempText = 2131165318;
			
			// aapt resource value: 0x7f070087
			public const int currentTempToggle = 2131165319;
			
			// aapt resource value: 0x7f07001b
			public const int custom = 2131165211;
			
			// aapt resource value: 0x7f070004
			public const int delete_alarm_layout = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int delete_button = 2131165190;
			
			// aapt resource value: 0x7f07008a
			public const int descriptionText = 2131165322;
			
			// aapt resource value: 0x7f07008b
			public const int descriptionToggle = 2131165323;
			
			// aapt resource value: 0x7f07006d
			public const int display_row = 2131165293;
			
			// aapt resource value: 0x7f070013
			public const int dummy = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int edit_alarm_layout = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int eventDateInput = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int eventDateText = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int eventNameInput = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int eventNameText = 2131165192;
			
			// aapt resource value: 0x7f070037
			public const int factRow = 2131165239;
			
			// aapt resource value: 0x7f070039
			public const int factToggle = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int fact_desc = 2131165240;
			
			// aapt resource value: 0x7f070084
			public const int fahrenheitText = 2131165316;
			
			// aapt resource value: 0x7f070085
			public const int fahrenheitToggle = 2131165317;
			
			// aapt resource value: 0x7f070054
			public const int fridayInput = 2131165268;
			
			// aapt resource value: 0x7f07003c
			public const int history_desc = 2131165244;
			
			// aapt resource value: 0x7f070045
			public const int hour = 2131165253;
			
			// aapt resource value: 0x7f070016
			public const int imageView1 = 2131165206;
			
			// aapt resource value: 0x7f070065
			public const int imageView2 = 2131165285;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout1 = 2131165202;
			
			// aapt resource value: 0x7f07007e
			public const int listTitle = 2131165310;
			
			// aapt resource value: 0x7f07007d
			public const int listTitleText = 2131165309;
			
			// aapt resource value: 0x7f070001
			public const int ltime_layout = 2131165185;
			
			// aapt resource value: 0x7f070088
			public const int maxTempText = 2131165320;
			
			// aapt resource value: 0x7f070089
			public const int maxTempToggle = 2131165321;
			
			// aapt resource value: 0x7f070046
			public const int minute = 2131165254;
			
			// aapt resource value: 0x7f070070
			public const int module = 2131165296;
			
			// aapt resource value: 0x7f07006f
			public const int module1Holder = 2131165295;
			
			// aapt resource value: 0x7f07006e
			public const int moduleImage = 2131165294;
			
			// aapt resource value: 0x7f07005f
			public const int moduleOrder = 2131165279;
			
			// aapt resource value: 0x7f07003f
			public const int moduleSection = 2131165247;
			
			// aapt resource value: 0x7f070041
			public const int module_layout = 2131165249;
			
			// aapt resource value: 0x7f070040
			public const int module_scroller = 2131165248;
			
			// aapt resource value: 0x7f07004c
			public const int mondayInput = 2131165260;
			
			// aapt resource value: 0x7f070007
			public const int nameInputLine = 2131165191;
			
			// aapt resource value: 0x7f07006c
			public const int navButton = 2131165292;
			
			// aapt resource value: 0x7f070076
			public const int newsCategorySpinner = 2131165302;
			
			// aapt resource value: 0x7f07001d
			public const int newsRow = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int news_desc = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int news_settings = 2131165216;
			
			// aapt resource value: 0x7f070043
			public const int picker_holder = 2131165251;
			
			// aapt resource value: 0x7f070061
			public const int pulldown = 2131165281;
			
			// aapt resource value: 0x7f07003b
			public const int quoteToggle = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public const int quote_desc = 2131165242;
			
			// aapt resource value: 0x7f070021
			public const int redditRow = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int reddit_desc = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int reddit_settings = 2131165220;
			
			// aapt resource value: 0x7f07000e
			public const int relativeLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070066
			public const int relativeLayout2 = 2131165286;
			
			// aapt resource value: 0x7f07000c
			public const int relativeLayout3 = 2131165196;
			
			// aapt resource value: 0x7f070069
			public const int relativeLayout4 = 2131165289;
			
			// aapt resource value: 0x7f070005
			public const int relativeLayout6 = 2131165189;
			
			// aapt resource value: 0x7f07007f
			public const int reminderContainer = 2131165311;
			
			// aapt resource value: 0x7f070072
			public const int reminderCount = 2131165298;
			
			// aapt resource value: 0x7f070074
			public const int reminderDeleteButton = 2131165300;
			
			// aapt resource value: 0x7f070073
			public const int reminderInput = 2131165299;
			
			// aapt resource value: 0x7f07007c
			public const int reminderList = 2131165308;
			
			// aapt resource value: 0x7f07007b
			public const int reminderScrollView = 2131165307;
			
			// aapt resource value: 0x7f07002f
			public const int remindersRow = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int reminders_desc = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int reminders_settings = 2131165234;
			
			// aapt resource value: 0x7f070049
			public const int repeatDaysInput = 2131165257;
			
			// aapt resource value: 0x7f070056
			public const int saturdayInput = 2131165270;
			
			// aapt resource value: 0x7f07000d
			public const int save_button = 2131165197;
			
			// aapt resource value: 0x7f070081
			public const int save_text = 2131165313;
			
			// aapt resource value: 0x7f070011
			public const int scrollView1 = 2131165201;
			
			// aapt resource value: 0x7f07003e
			public const int set_alarm_window = 2131165246;
			
			// aapt resource value: 0x7f07006b
			public const int setting_title = 2131165291;
			
			// aapt resource value: 0x7f070063
			public const int settings = 2131165283;
			
			// aapt resource value: 0x7f070057
			public const int settings_container = 2131165271;
			
			// aapt resource value: 0x7f07005b
			public const int settings_row = 2131165275;
			
			// aapt resource value: 0x7f070014
			public const int single = 2131165204;
			
			// aapt resource value: 0x7f07005d
			public const int snooze = 2131165277;
			
			// aapt resource value: 0x7f070059
			public const int snoozeBar = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int snoozeOutput = 2131165274;
			
			// aapt resource value: 0x7f070058
			public const int snooze_row = 2131165272;
			
			// aapt resource value: 0x7f07005e
			public const int speech = 2131165278;
			
			// aapt resource value: 0x7f07007a
			public const int subredditInput = 2131165306;
			
			// aapt resource value: 0x7f070079
			public const int subredditText = 2131165305;
			
			// aapt resource value: 0x7f07004a
			public const int sundayInput = 2131165258;
			
			// aapt resource value: 0x7f07003d
			public const int tdihToggle = 2131165245;
			
			// aapt resource value: 0x7f070052
			public const int thursdayInput = 2131165266;
			
			// aapt resource value: 0x7f070044
			public const int timescrollers = 2131165252;
			
			// aapt resource value: 0x7f07006a
			public const int title_row = 2131165290;
			
			// aapt resource value: 0x7f070071
			public const int toggle = 2131165297;
			
			// aapt resource value: 0x7f070036
			public const int toggle_text = 2131165238;
			
			// aapt resource value: 0x7f07005c
			public const int tone = 2131165276;
			
			// aapt resource value: 0x7f070033
			public const int trafficRow = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int traffic_desc = 2131165237;
			
			// aapt resource value: 0x7f07004e
			public const int tuesdayInput = 2131165262;
			
			// aapt resource value: 0x7f070026
			public const int twitterRow = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int twitter_desc = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int twitter_settings = 2131165225;
			
			// aapt resource value: 0x7f070083
			public const int usernameInput = 2131165315;
			
			// aapt resource value: 0x7f070082
			public const int usernameText = 2131165314;
			
			// aapt resource value: 0x7f07001a
			public const int view1 = 2131165210;
			
			// aapt resource value: 0x7f070051
			public const int view10 = 2131165265;
			
			// aapt resource value: 0x7f070053
			public const int view11 = 2131165267;
			
			// aapt resource value: 0x7f070055
			public const int view12 = 2131165269;
			
			// aapt resource value: 0x7f07001c
			public const int view2 = 2131165212;
			
			// aapt resource value: 0x7f070025
			public const int view3 = 2131165221;
			
			// aapt resource value: 0x7f07002a
			public const int view4 = 2131165226;
			
			// aapt resource value: 0x7f07004b
			public const int view7 = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int view8 = 2131165261;
			
			// aapt resource value: 0x7f07004f
			public const int view9 = 2131165263;
			
			// aapt resource value: 0x7f070015
			public const int weatherRow = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int weather_desc = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int weather_settings = 2131165209;
			
			// aapt resource value: 0x7f070050
			public const int wednesdayInput = 2131165264;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int alarm_display = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int countdown = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int create_module = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int manage_alarms = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int module_display = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int module_holder = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int module_setting_row = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int new_reminder_template = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int news = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int reddit = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int reminders = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int save_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int twitter = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int weather = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int weather_settings = 2130968591;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int news_prompt = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
