// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Clockwise.iOS
{
	public partial class ViewController : UIViewController
	{
		public ViewController (IntPtr handle) : base (handle)
		{
			
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			alarmToggle.TouchUpInside += delegate {
				Console.WriteLine("toggle alarm");
			};

			settingsButton.TouchUpInside += delegate
			{
				Console.WriteLine("settings button");
			};

			addModuleButton.TouchUpInside += delegate
			{
				Console.WriteLine("add module");
			};
		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
		}
	}
}
